name: Build-depoly-Crago-react

on: workflow_dispatch

jobs:
  Build-Crago: 
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./dev
    steps:
      - name: clone repo 
      - uses: actions/checkout@v3
      - name: setup repo
      - uses: actions/setup-node@v3
        with :
           node-version: 16
      
      - run: npm install 
      - run: npm run build
      - name: Setup tmate session
      - uses: mxschmitt/action-tmate@v3


