name: Build-depoly-Crago-react

on: workflow_dispatch

jobs:
  Build-Crago: 
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./dev
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: check work dir
        run: pwd 
      - name: setup nodejs 
        uses: actions/setup-node@v3
        with :
           node-version: 16
      - name: install node dependencies 
        run: npm install
      - name: run craco build
        run: npm run build
      - name: upload build to artifacts for production 
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: ./dev/build/
          retention-days: 1

      # - name: Setup Debug Session
      #   uses: csexton/debugger-action@master
  Upload-prod-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
         name: production-build
    
      - name: Display structure of downloaded files
        run: ls -R

 


