name: Build-depoly-Crago-react

on: workflow_dispatch

jobs:
  Build-Crago: 
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./dev
    steps:
      - name: Setup tmate remote ssh session for debugging
        uses: mxschmitt/action-tmate@v3
      - name: clone repo
        uses: actions/checkout@v3
      - name: check work dir
        run: pwd 
      - name: setup nodejs 
        uses: actions/setup-node@v3
        with :
           node-version: 16
      - name: install node dependencies 
        run: npm install
      - name: run craco build
        run: npm run build
                  
 


